#!/usr/bin/env python3
"""Deterministic Markdown -> HTML/CSS -> PDF renderer (WeasyPrint).

Replaces the old LaTeX/xelatex path and the per-run improvised fpdf2 scripts
with ONE committed renderer. Produces a branded, chart-embedded, bilingual PDF
from the final markdown report plus the pipeline's JSON artifacts.

Usage:
    .venv/bin/python3 templates/render_pdf.py <workspace> <date>

Inputs (under {workspace}):
    final/{date}/{daily_report|weekly_report}.md   — the report body
    decision/{date}/final_decision.json            — rating box
    quant/{date}/quant_summary.json                — price + key metrics
    valuation/{date}/valuation_summary.json        — fair value / margin of safety
    profile/company_profile.json                   — company meta + market cap
    exports/{date}/pdf/charts/*.svg                — charts (from charts.py)
    resolved_config.json                           — language + run_mode

Output:
    exports/{date}/pdf/report.pdf   (and report.html for debugging)

Never crashes the (non-critical) export stage: missing artifacts degrade
gracefully to "—" / omitted sections.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

import markdown as md
from jinja2 import Template
from weasyprint import HTML

TEMPLATES_DIR = Path(__file__).resolve().parent

# ---- bilingual UI strings (ported from equity_research.cls) ----
STRINGS = {
    "en": {
        "rating": "Rating", "confidence": "Confidence", "horizon": "Horizon",
        "price": "Price", "fair_value": "Fair Value (DCF)",
        "margin_of_safety": "Margin of Safety", "market_cap": "Market Cap",
        "valuation": "Valuation", "mode_daily": "Daily Report",
        "mode_weekly": "Weekly Report", "exhibits": "Exhibits",
        "disclaimer": ("<strong>Disclaimer:</strong> This report is generated by "
            "MarketMind-AlphaEngine, an automated equity research system. It is "
            "provided for informational purposes only and does not constitute "
            "investment advice, a recommendation, or an offer to buy or sell any "
            "security. Past performance is not indicative of future results. Users "
            "should conduct their own due diligence."),
        "sources_list": ("<strong>Sources:</strong> Yahoo Finance, NewsAPI, "
            "SEC EDGAR, FRED, web search."),
        "verdict": {"cheap": "Cheap", "fair": "Fair", "expensive": "Expensive",
                    "unknown": "—"},
        "m_1d": "1D", "m_5d": "5D", "m_1m": "1M", "m_3m": "3M", "m_rsi": "RSI(14)",
    },
    "ch": {
        "rating": "评级", "confidence": "置信度", "horizon": "时间维度",
        "price": "现价", "fair_value": "内在价值(DCF)",
        "margin_of_safety": "安全边际", "market_cap": "市值",
        "valuation": "估值判断", "mode_daily": "每日市场跟踪",
        "mode_weekly": "每周市场跟踪", "exhibits": "图表附录",
        "disclaimer": ("<strong>免责声明：</strong>本报告由 MarketMind-AlphaEngine "
            "自动生成，仅供参考，不构成投资建议、推荐或任何证券买卖要约。过往表现不代表未来收益。"
            "用户应自行研判。"),
        "sources_list": ("<strong>数据来源：</strong>Yahoo Finance、NewsAPI、"
            "SEC EDGAR、FRED、网络搜索。"),
        "verdict": {"cheap": "低估", "fair": "合理", "expensive": "高估",
                    "unknown": "—"},
        "m_1d": "1日", "m_5d": "5日", "m_1m": "1月", "m_3m": "3月", "m_rsi": "RSI(14)",
    },
}

CHART_LABELS = {
    "en": {"price_chart": "Price action & technicals",
           "relative_chart": "Relative strength", "peer_chart": "Peer 5-day returns"},
    "ch": {"price_chart": "股价走势与技术指标",
           "relative_chart": "相对强弱", "peer_chart": "同业5日涨跌幅"},
}


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def fmt_price(v):
    return f"${v:,.2f}" if isinstance(v, (int, float)) else "—"


def fmt_pct(v):
    return f"{v:+.2f}%" if isinstance(v, (int, float)) else "—"


def fmt_big(v):
    if not isinstance(v, (int, float)) or v <= 0:
        return "—"
    for unit, div in (("T", 1e12), ("B", 1e9), ("M", 1e6)):
        if abs(v) >= div:
            return f"${v/div:.2f}{unit}"
    return f"${v:,.0f}"


def sign_class(v):
    if not isinstance(v, (int, float)):
        return ""
    return "pos" if v > 0 else ("neg" if v < 0 else "")


def strip_md_header(text: str) -> str:
    """Drop the leading '# Title' and the '**Date:** ...' meta line (shown on cover)."""
    lines = text.splitlines()
    out, dropped_title = [], False
    for i, ln in enumerate(lines):
        s = ln.strip()
        if not dropped_title and s.startswith("# "):
            dropped_title = True
            continue
        if dropped_title and s.startswith("**Date:"):
            continue
        if dropped_title and out == [] and s in ("---", ""):
            continue
        out.append(ln)
    return "\n".join(out)


def main():
    if len(sys.argv) < 3:
        print("usage: render_pdf.py <workspace> <date>", file=sys.stderr)
        sys.exit(2)

    workspace = Path(sys.argv[1])
    date = sys.argv[2]
    ticker = workspace.name

    cfg = load_json(workspace / "resolved_config.json") or {}
    lang = "ch" if cfg.get("language") == "ch" else "en"
    run_mode = cfg.get("run_mode", "daily")
    S = STRINGS[lang]
    S = {**S, "mode": S["mode_weekly"] if run_mode == "weekly" else S["mode_daily"]}

    basename = "weekly_report" if run_mode == "weekly" else "daily_report"
    pdf_dir = workspace / "exports" / date / "pdf"
    pdf_dir.mkdir(parents=True, exist_ok=True)
    chart_dir = pdf_dir / "charts"

    report_md = (workspace / "final" / date / f"{basename}.md")
    if not report_md.exists():
        print(f"render_pdf: report not found: {report_md}", file=sys.stderr)
        sys.exit(1)

    profile = load_json(workspace / "profile" / "company_profile.json") or {}
    decision = load_json(workspace / "decision" / date / "final_decision.json") or {}
    quant = load_json(workspace / "quant" / date / "quant_summary.json") or {}
    val = load_json(workspace / "valuation" / date / "valuation_summary.json") or {}

    # ---- markdown body -> HTML ----
    body_md = strip_md_header(report_md.read_text(encoding="utf-8"))
    body_html = md.markdown(
        body_md,
        extensions=["tables", "fenced_code", "attr_list", "sane_lists", "footnotes"],
    )

    # If the writer didn't anchor charts inline, append an Exhibits section so
    # charts ALWAYS appear (the old pipeline dropped them entirely).
    if "charts/" not in body_html and chart_dir.is_dir():
        figs = []
        for stem in ("relative_chart", "price_chart", "peer_chart"):
            if (chart_dir / f"{stem}.svg").exists():
                cap = CHART_LABELS[lang][stem]
                figs.append(f'<figure><img src="charts/{stem}.svg">'
                            f'<figcaption>{cap}</figcaption></figure>')
        if figs:
            body_html += f'\n<h2>{S["exhibits"]}</h2>\n' + "\n".join(figs)

    # ---- rating box values (authoritative, from JSON) ----
    dec = (decision.get("decision") or "HOLD").upper()
    price = quant.get("latest_close")
    if not isinstance(price, (int, float)):
        price = val.get("current_price")

    mos = val.get("margin_of_safety")
    rng = (val.get("intrinsic_range") or {}) if val.get("applicable") else {}
    if rng.get("base") is not None:
        fair_value = fmt_price(rng.get("base"))
        if rng.get("bear") is not None and rng.get("bull") is not None:
            fair_value += f" ({fmt_price(rng['bear'])[1:]}–{fmt_price(rng['bull'])[1:]})"
    else:
        fair_value = "—"

    verdict_key = (val.get("verdict") or "unknown") if val.get("applicable") else "unknown"
    verdict = S["verdict"].get(verdict_key, "—")

    returns = quant.get("returns") or {}
    tech = quant.get("technical") or {}
    metrics = [
        {"k": S["m_1d"], "v": fmt_pct(returns.get("1d")), "cls": sign_class(returns.get("1d"))},
        {"k": S["m_5d"], "v": fmt_pct(returns.get("5d")), "cls": sign_class(returns.get("5d"))},
        {"k": S["m_1m"], "v": fmt_pct(returns.get("1m")), "cls": sign_class(returns.get("1m"))},
        {"k": S["m_3m"], "v": fmt_pct(returns.get("3m")), "cls": sign_class(returns.get("3m"))},
        {"k": S["m_rsi"], "v": (f"{tech.get('rsi_14'):.1f}"
                                if isinstance(tech.get("rsi_14"), (int, float)) else "—"), "cls": ""},
    ]

    ctx = {
        "lang": lang, "S": S,
        "css": (TEMPLATES_DIR / "report.css").read_text(encoding="utf-8"),
        "company": profile.get("name") or profile.get("long_name") or ticker,
        "ticker": ticker,
        "exchange": profile.get("exchange") or "",
        "sector": profile.get("sector") or "",
        "date": date,
        "decision": dec,
        "confidence": (f"{decision.get('confidence'):.2f}"
                       if isinstance(decision.get("confidence"), (int, float)) else "—"),
        "horizon": decision.get("horizon") or "—",
        "price": fmt_price(price),
        "fair_value": fair_value,
        "margin_of_safety": (f"{mos*100:+.0f}%" if isinstance(mos, (int, float)) else "—"),
        "mos_class": sign_class(mos),
        "market_cap": fmt_big(profile.get("market_cap")),
        "verdict": verdict,
        "metrics": metrics,
        "body_html": body_html,
    }

    html_str = Template((TEMPLATES_DIR / "report.html.j2").read_text(encoding="utf-8")).render(**ctx)
    (pdf_dir / "report.html").write_text(html_str, encoding="utf-8")

    HTML(string=html_str, base_url=str(pdf_dir)).write_pdf(str(pdf_dir / "report.pdf"))
    print(f"render_pdf: wrote {pdf_dir/'report.pdf'} ({lang}, {run_mode})")


if __name__ == "__main__":
    main()
